version: '3.8'

services:
  backend:
    build:
      context: ./myApp/myApp
      dockerfile: Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MyConnectionString=Server=sqlserver;Database=ticketdb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
  
  frontend:
    build:
      context: "./TicketTable"  
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
